# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Use Android Studio's bundled JDK 17 (JBR) for both running Gradle and compilation
# org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
